# Generated by Django 3.2.13 on 2022-06-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
