# Generated by Django 3.2.13 on 2022-06-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('not_active', 'not_active')], max_length=20),
        ),
    ]
