# Generated by Django 3.2.13 on 2022-06-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0009_auto_20220624_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product/noimage.jpg', upload_to='product/'),
        ),
    ]
