# Generated by Django 3.2.13 on 2022-06-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0015_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Getting Ready for Packing', 'Getting Ready for Packing'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=30),
        ),
    ]
