# Generated by Django 3.2.13 on 2022-06-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
