# Generated by Django 3.2.13 on 2022-06-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0018_order_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_rating',
        ),
    ]
