# Generated by Django 3.2.13 on 2022-07-04 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0023_auto_20220704_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimate_dd',
            field=models.DateField(default=datetime.date(2022, 7, 11)),
        ),
    ]
