# Generated by Django 3.2.13 on 2022-07-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0028_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prod_image',
            field=models.ImageField(blank=True, default='product/noimage.jpg', upload_to='product/'),
        ),
    ]
